sudo: require
language: node_js
git:
  submodules: false

services:
  - docker
 
env:
#  global:
#   - IMAGE_NAME=ubuntu:latest
  matrix:
    - DOCKERFILE=Dockerfile.fresh node_ver=8
    - DOCKERFILE=Dockerfile.fresh node_ver=10
    - DOCKERFILE=Dockerfile.fresh node_ver=12
    - DOCKERFILE=Dockerfile.migration node_ver=8
    - DOCKERFILE=Dockerfile.migration node_ver=10
    - DOCKERFILE=Dockerfile.migration node_ver=12
    - DOCKERFILE=Dockerfile.outdated node_ver=8
    - DOCKERFILE=Dockerfile.outdated node_ver=10
    - DOCKERFILE=Dockerfile.outdated node_ver=12

#before_script:
#  - version="$(awk '$2 == "LOKI_LAUNCHER_VERSION" { print $3; exit }' Dockerfile)"
#  - docker pull "$IMAGE_NAME" || true

before_install:
  - docker build --build-arg node_ver=$node_ver -f $DOCKERFILE -t loki-project/loki-launcher .
#  - if [[ $MIGRATION ]]; then ; fi

script:
  # npm upgrade test/status/prequal/systemd/upgrade/start/stop test
  - docker run --cap-add NET_BIND_SERVICE --cap-add NET_ADMIN --network=host --privileged loki-project/loki-launcher /bin/sh -c "cd /usr/src/app && npm install -g && loki-launcher status && loki-launcher prequal && loki-launcher check-systemd && loki-launcher download-binaries && loki-launcher fix-perms root && loki-launcher config-view && loki-launcher start-debug --ignore-storage-server-port-check && sleep 30 && loki-launcher status && loki-launcher stop"
  - docker run --cap-add NET_BIND_SERVICE --cap-add NET_ADMIN --network=host --privileged loki-project/loki-launcher /bin/sh -c "cd /usr/src/app && npm install -g && loki-launcher status --testnet && loki-launcher prequal-debug --testnet && loki-launcher check-systemd --testnet && loki-launcher download-binaries --testnet && loki-launcher fix-perms root --testnet && loki-launcher config-view --testnet && loki-launcher start-debug --testnet --ignore-storage-server-port-check && sleep 30 && loki-launcher status --testnet && loki-launcher stop --testnet"

#script:
#  - docker build --pull --cache-from "$IMAGE_NAME" --tag "$IMAGE_NAME" .

#after_script:
#  - docker images
